#!/bin/sh

ADMIN_USERNAME="$1"
ADMIN_PASSWORD="$2"
DB_NAME="$3"
DP_FILE="$4"
HOST="$5"
PORT="$6"

/opt/dmdbms/bin/dimp $ADMIN_USERNAME/$ADMIN_PASSWORD@$HOST:$PORT file=$DP_FILE owner=$DB_NAME TABLE_EXISTS_ACTION=TRUNCATE PRIMARY_CONFLICT=OVERWRITE2
